### ISSUE TITLE
Fazer um manual pra iniciantes

### ISSUE THREAD

**Issue by brunoabdon** [brunoabdon/domino#2]
Fazer um manual pra iniciantes, que a pessoa leia e saiba implementar um Jogador e botar pra rodar uma partida, pelo menos.

**Comment by Danielccosta63** [comment]
Esse manual foi feito?

**Comment by brunoabdon** [comment]
Ainda não. Mas deveria!

**Comment by Danielccosta63** [comment]
Mas esse projeto ja está finalizado e funcionando?

**Comment by Danielccosta63** [comment]
Estou em um projeto da disciplina de POO para fazer refatoração de códigos seguindo padrões de projeto, como achei o seu projeto bem documentado eu escolhi ele. Mas estou com dificuldades de executa-lo em minha maquina.

**Comment by brunoabdon** [comment]
Oi,  Daniel. O projeto funciona sim. Eu vou fazer a documentação. Por enquanto, te explico por aqui.

Você precisa ter a [JDK 8](http://www.oracle.com/technetwork/java/javase/downloads/index.html) e o [Maven](https://maven.apache.org/) instalado.

primeiro, clona o projeto:

`$ git clone git@github.com:brunoabdon/domino.git`

Entra no diretório...

`$ cd domino`

Faz o build:

`$ mvn package`

Entra no diretório...

`$ cd target`

Pra executar, é preciso ter um xml chamado `domino-config.xml` no diretório atual. Esse arquivo diz quais serão as implementações de Jogadores que vão jogar. Tem um arquivo de exemplo no diretório [`/src/test/resources/domino-config.xml`](https://github.com/brunoabdon/domino/blob/master/src/test/resources/domino-config.xml). Vamos usar ele:

`$ cp ../src/test/resources/domino-config.xml .`

agora podemos rodar uma partida de dominó:

`java -jar domino-1.0-SNAPSHOT.jar`

A partida ocorrem em menos de 1 segundo, normalmente. E vai sendo logada no prompt.

Funcionou?

**Comment by Danielccosta63** [comment]
Funcionou sim, Obrigado.

**Comment by brunoabdon** [comment]
Daniel, interessante esse teu projeto. Se for ficando legal a gente até incorpora tuas modificações ao código do programa.

**Comment by Danielccosta63** [comment]
Após a refatoração farei um pull request .

**Comment by brunoabdon** [comment]
Fechando. Documentação deu uma boa evoluida.
Ver [Javadoc](http://brunoabdon.github.io/domino/apidocs/) e o READ.ME
